name: vetoapp
description: "VetoApp National Portal"
publish_to: 'none'
version: 1.4.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  audioplayers: ^6.1.2
  dartz: ^0.10.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  vetoapp_demo:
    path: /home/sadeq/workspace/VetoAppDemo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/startup.wav

  fonts:
    - family: B Mitra
      fonts:
        - asset: assets/fonts/BMitra.ttf
        - asset: assets/fonts/BMitra-Bold.ttf
          weight: 700
