[unix_http_server]
file=/tmp/supervisor-worker.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord-worker.pid
childlogdir=/tmp
logfile_maxbytes=0

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor-worker.sock

[program:queue-worker]
command=/usr/local/bin/php /var/www/html/artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600 --no-interaction
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=3600
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
