FROM nginx:1.28-alpine

COPY app/public/ /var/www/html/public/
COPY deploy/nginx/entrypoint.sh /usr/local/bin/vetoapp-nginx-entrypoint
COPY deploy/nginx/templates/ /etc/nginx/vetoapp-templates/

RUN rm -f /etc/nginx/conf.d/default.conf \
    && mkdir -p /var/www/certbot /var/www/html/storage /var/www/wordpress \
    && ln -sfn ../storage/app/public /var/www/html/public/storage \
    && chmod +x /usr/local/bin/vetoapp-nginx-entrypoint

ENTRYPOINT ["/usr/local/bin/vetoapp-nginx-entrypoint"]
